# Generated by Django 2.2.2 on 2019-07-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='rating',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
